# SPDX-FileCopyrightText: Andrei Gherzan <andrei@gherzan.com>
#
# SPDX-License-Identifier: MIT

name: 'Git Mirror-Me (GMm) GitHub Action'
description: >
  This GitHub action provides the ability to mirror a repository to any other
  git repository.
branding:
  icon: 'refresh-cw'
  color: 'green'
inputs:
  source-repository:
    description: 'Sets the source repository for the mirror operation.'
    required: false
  destination-repository:
    description: 'Sets the destination repository for the mirror operation.'
    required: true
  debug:
    description: 'Runs the git-mirror-me tool in debug mode.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -source-repository
    - ${{ inputs.source-repository }}
    - -destination-repository
    - ${{ inputs.destination-repository }}
    - -debug
    - ${{ inputs.debug }}
