# SPDX-FileCopyrightText: Andrei Gherzan <andrei@gherzan.com>
#
# SPDX-License-Identifier: MIT

name: 'Git Mirror-Me (GMm) GitHub Action'
description: >
  This GitHub action provides the ability to mirror a repository to any other
  git repository.
branding:
  icon: 'refresh-cw'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
